### ISSUE TITLE
Error: Config file 'mkdocs.yml' does not exist.

### ISSUE THREAD

**Issue by mnahmad** [minidocks/mkdocs#5]
Hi 
I am using the image on macOS Catalina (10.15.7), when starting server using the following command 

```docker run --rm -v "`pwd`:/app" -w /app/doc -p 8000:8000 minidocks/mkdocs serve -a 0.0.0.0:8000 -t material```

I get the following error

> INFO     -  Building documentation...
> Error: Config file 'mkdocs.yml' does not exist.

similar issue is discussed [here](https://github.com/squidfunk/mkdocs-material/issues/1076) but the solution is not working for me. 

thanks

**Comment by sl-antonybasbug** [comment]
You have to first run this command : 

`docker run --rm -v "`pwd`:/app" -w /app minidocks/mkdocs new doc`

Then : 

`docker run --rm -v "`pwd`:/app" -w /app/doc -p 8000:8000 minidocks/mkdocs serve -a 0.0.0.0:8000 -t material`

**Comment by mnahmad** [comment]
thanks for help, every thing is working for me now.
